### ISSUE TITLE
Transformers Version MiniForge

### ISSUE THREAD

**Issue by rezamousavi** [conda-forge/transformers-feedstock#99] opened 2022-09-02 02:35 UTC
Hi,

I'm trying to install transformers. I checked on the website and the latest version of transformers on MiniForge is 4**. But the following installs transforms 2.1.1. I tried a variety of things including declaring the version I'm looking for. Still no luck. Running Mac OS M1 Pro. Tensorflow, PyTorch, Kera, spaCy work ok.
Thanks!

**Comment by hmaarrfk** [comment] 2022-09-02 03:52
Hi Thank you for raising the issue. 

Raising it on the Miniforge repository isn't the best place to do so. The transformers experts monitor the `transformers-feedstock` repository. I moved it here to ensure we get their attention.

However, the information you provided is very thin. Depending on the issue template you used. you may have skipped over some of the requested information.

All sections listed in https://github.com/conda-forge/conda-forge.github.io/blob/main/.github/ISSUE_TEMPLATE/error_template.yml which should automatically open when you create an issue are really important for us to help you out.

If you could reply with the rested information in the template, or simply close this issue and open a new one here, that would help get you the answers you are seeking.

**Comment by setu4993** [comment] 2022-09-04 00:38
@rezamousavi : Thanks for opening this issue, happy to help fix this.

+1 to what @hmaarrfk said above, if you can help fill out the template, that'd make it much easier to help.

**Comment by Tobias-Fischer** [comment] 2022-09-26 04:38
The issue is that https://github.com/conda-forge/tokenizers-feedstock/ is not yet migrated to python=3.10. If you create a new environment with python=3.9 (or change your existing env to py39), you will get around this issue.

**Comment by setu4993** [comment] 2023-06-15 03:09
I'm going to close this because:
1. `tokenizers` doesn't appear to be blocking [installs on Python 3.10](https://github.com/conda-forge/tokenizers-feedstock/blob/main/recipe/meta.yaml#L31-L45).
2. Inactivity and lack of interaction from OP for >6 months.

**Closed by setu4993** 2023-06-15 03:09 UTC
Labels: question
